language: java

# Especifica la versión de Java
jdk:
  - openjdk17

# Sistema operativo
os: linux
dist: focal

# Cache para Maven dependencies
cache:
  directories:
    - $HOME/.m2

# Variables de entorno para Travis
env:
  global:
    - DB_URL=jdbc:h2:mem:testdb
    - DB_USERNAME=sa
    - DB_PASSWORD=
    - JWT_SECRET=test-secret-key-for-travis-ci-tests

# Comandos antes de ejecutar el script
before_script:
  - echo "Configurando entorno de pruebas..."
  - echo "Java version:"
  - java -version
  - echo "Maven version:"
  - mvn -version

# Script principal - Tests funcionando correctamente con H2
script:
  - mvn clean test

# Solo compilar si los tests pasan
after_success:
  - mvn clean compile
  - echo "✅ Tests ejecutados exitosamente!"

# En caso de fallo
after_failure:
  - echo "❌ Los tests fallaron"
  - cat target/surefire-reports/*.txt

# Configuración de notificaciones
notifications:
  email:
    recipients:
      - alexpardox@gmail.com
    on_success: change
    on_failure: always

# Ramas a incluir
branches:
  only:
    - main
    - develop
