language: java

# Configuración específica para Travis CI
dist: focal
jdk: openjdk17

# Cache Maven
cache:
  directories:
    - $HOME/.m2

# Test básico sin dependencias
script:
  - mvn test -Dtest="SimpleTest" -q

# Solo incluir estas ramas
branches:
  only:
    - main
    - develop
