language: java

# Especifica la versión de Java
jdk:
  - openjdk17

# Sistema operativo
os: linux
dist: focal

# Cache para Maven dependencies
cache:
  directories:
    - $HOME/.m2

# Variables de entorno mínimas para Travis
env:
  global:
    - MAVEN_OPTS="-Xmx1024m"

# Comandos antes de ejecutar el script
before_script:
  - echo "Configurando entorno de pruebas..."
  - echo "Java version:"
  - java -version
  - echo "Maven version:"
  - mvn -version

# Script principal - Solo test básico sin dependencias
script:
  - echo "🧪 Ejecutando test súper simple..."
  - mvn test -Dtest="SimpleTest"
  - echo "✅ Test básico completado"

# Solo mensaje de éxito
after_success:
  - echo "✅ Test básico completado exitosamente en Travis CI!"

# En caso de fallo
after_failure:
  - echo "❌ El test básico falló"
  - echo "Revisar logs de Maven arriba"

# Configuración de notificaciones
notifications:
  email:
    recipients:
      - alexpardox@gmail.com
    on_success: change
    on_failure: always

# Ramas a incluir
branches:
  only:
    - main
    - develop
