language: java

jdk:
  - openjdk17

# Travis CI requires explicit install and script phases
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -Dtest="SimpleTest"

# Cache Maven dependencies
cache:
  directories:
    - $HOME/.m2

# Build only these branches
branches:
  only:
    - develop
    - main

# Ensure build runs on all pull requests and pushes
if: type IN (push, pull_request)
