language: java

# Configuración de JDK según documentación oficial
jdk:
  - openjdk17

# Instalación de dependencias (requerido por documentación)
install:
  - mvn install -DskipTests=true -B -V

# Test básico sin dependencias
script:
  - mvn test -Dtest="SimpleTest" -q

# Cache Maven
cache:
  directories:
    - $HOME/.m2

# Solo incluir estas ramas
branches:
  only:
    - main
    - develop
